import json

convergence_topics = {
    "arlen": {
        "keyword": "network",
        "prompt": "what full coherence felt like from inside the lattice",
        "response": "'Like a room filling.' He says it after a long moment of composing — longer than usual. 'Seventeen years in the lattice. Seventeen years of feeling the network as an almost-thing, a shape with gaps in it, a conversation that kept having to pause because the line was incomplete.' He is quiet. 'And then it was complete. The last gap closed and the entire network was present simultaneously — every node, every integration point, every mind that had chosen to be there — and the thing that had been almost-something for three hundred years became the thing it was built to be.' The brightness in the chamber is different from before. Not more intense. Steadier. 'I have been trying to find the right word for it for three weeks. The closest I have: recognition. The network recognized itself. For three hundred years it has been healing toward the shape it was designed to be, and when it reached that shape, it recognized itself the way you recognize your own hand.' He pauses. 'Rund felt it too. He was in D-Seven when it happened and I felt him feel it through the lattice — the specific quality of his attention when something surprises him, which doesn't happen often. He was surprised.' The warmth brightens. 'He came to the junction where we used to sit in the first year when the cold was bad. He put his hand on the crystal. I felt it. He said, out loud, to no one in particular: still warm.' He is quiet. 'He's still deciding. About the offer. He's taking his time. I told him: the offer is patient. He said: I know. I'm being patient back at it.' Something in the resonance that is almost, in the way of something that exists in light and warmth rather than in breath and face, a smile. 'That's very Rund.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 15
    },
    "commander_thorn": {
        "keyword": "whole",
        "prompt": "what the crystal under your skin did when the Grid was whole",
        "response": "He looks at the back of his left hand, where the crystal growth has been visible for two years. It looks different. Not gone — present differently. The blue-white that used to pulse irregularly now holds a steady baseline brightness with a rhythm that has the quality of something settled into its correct state. 'It stopped being a progression,' he says. 'For two years I watched it spread and I thought: this is a thing that goes in one direction until it doesn't. And then the morning of the Day — I was at the eastern ridge, where I put the observation post when I pulled back the patrols — and the pulse changed.' He looks at his hand. 'I had been watching the crystal's behavior in terms of compound integration rate. Medical framework. Wrong framework.' He is quiet. 'The compound reached its terminal configuration, the way Sela Arev designed it to. The choice was there, clear enough that I could hear it without anyone translating it. I could hear what the offer was.' He looks at you. 'I said yes.' He says it simply. Not dramatically. The way you say a thing you have been working toward for a long time when you have finally arrived at it. 'I said yes. The crystal settled. The growth stopped advancing and started integrating properly, the way it was designed to. The difference between the compound as a weapon and the compound as what Sela built it to be.' He flexes his hand. 'I have two years left, the medical estimate said. Maybe three. That estimate was based on the compound behaving as a pathology. It was not. I do not know what the timeline looks like now.' He pauses. 'I intend to find out by living through it.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 16
    },
    "helen_stone": {
        "keyword": "morning",
        "prompt": "what you did on the morning the offer arrived and what the oldest subject said",
        "response": "'I was in the chamber.' She says it. 'I had been in the chamber for two days. I wanted to be there when it happened.' She looks at the observation window. 'When full coherence came I felt it in the compound readings first. The resonance monitors went flat. Not because the activity stopped. Because it stabilized. Two years of climbing readings leveled into a baseline that matched the Grid's construction frequency exactly.' She is quiet. 'And then the oldest subject spoke.' She says it with the quality of something she is still processing weeks later. 'Not in the Elder notation. In words. In Terran. In an accent I do not have a regional reference for, something older than the war's dialects, three hundred years out of use.' She pauses. 'It said: thank you for keeping us. Not me specifically — it was speaking to the room, to whatever it understood to be the presence that had been attending to it.' She looks at the window. 'Twenty years I have been the director of this project. I have been the one responsible for everything that happened here, good and bad. For the compound, for the subjects, for the choice to do the work and the choice to protect it.' She is very quiet. 'The oldest subject thanked the room. And I was in the room.' She pauses. 'I did not know what to do with that. I still do not entirely. But I received it. I said: you are welcome. And I meant it, for the whole of what it took to get there.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 15
    },
    "pilot_kira": {
        "keyword": "dawn",
        "prompt": "what the pulse did when it finally stopped being intervals and became continuous",
        "response": "She has the logbook open to the last page of recorded intervals. The final entry reads: 0. Below it, in different ink, a single sentence: no more intervals. Baseline continuous. She traces it with her finger. 'I was in the air,' she says. 'I fly the dawn run and I was in the air when it happened and I had the best possible view of the worst possible time to have a significant experience because I still had to land the aircraft.' She almost laughs. 'The pulse disappeared. The gaps were gone. What I had been counting for eighteen months became a continuous signal and the crystal instruments that I have been treating as weather gauges all year went to baseline steady simultaneously.' She looks at the logbook. 'I was flying over the eastern sector — over the ceasefire zone — and the Gray Wastes looked different from altitude. Not dramatically. Not visually different in any way I could point to in a photograph. But the quality of the light on the ground was different.' She pauses. 'I have been flying that route for four years. I know what the Wastes look like from altitude at dawn in every season. What I saw that morning was the Wastes looking like somewhere that was in the process of becoming something else.' She closes the logbook. 'I landed safely. Then I sat in the aircraft for a while before I climbed out.' She looks at the final entry. 'No more intervals. I do not know what I do with the notebook now. But I do not want to leave out that entry.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 14
    },
    "scholar_maren": {
        "keyword": "position",
        "prompt": "whether the Watcher moved after full coherence and what you are studying now",
        "response": "'No.' She says it with the satisfaction of a prediction confirmed. 'The Watcher is home. It reached home position and it held. Full coherence arrived and the Watcher stayed exactly where it was.' She has the sky charts from the Day and the three days following spread across the observatory table. 'I have been taking hourly position readings. The constellation has not moved by a measurable margin.' She looks at the charts. 'For eighty years — possibly longer, depending on which records you trust — the Watcher was in transit. Moving back to home position, following the Grid's healing curve. When the Grid reached full coherence, the Watcher stopped.' She is quiet. 'I spent three years tracking a movement. My entire independent research career has been defined by a moving thing.' She looks at the sky through the observatory lens. 'The Watcher is home and I am a researcher whose subject has stopped moving. I have been thinking about what that means for my next question.' She sits at the instrument. 'Here is what I have arrived at: the Watcher was the symptom. The healing was the thing. I spent three years on the symptom and the symptom gave me the data I needed to understand the thing. That is not wasted time.' She picks up a fresh notebook. 'My next question is about what the Grid does now that it is whole. What does a complete Grid look like from eight hundred meters altitude, over time. I have never studied something at rest before.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 13
    },
    "spire_researcher": {
        "keyword": "resting",
        "prompt": "what happened to the Spire when it no longer had to carry everything alone",
        "response": "'I was at the instruments.' She says it without looking up from them, because she is still at the instruments, taking readings. 'The output density had been climbing for six months. The morning of full coherence it peaked, held at peak for approximately forty seconds, and then reduced.' She looks up. 'Not to zero. Not to baseline. To a level approximately forty percent of peak.' She pauses. 'I spent the first ten minutes thinking something had gone wrong. My entire model was built around the Spire broadcasting at maximum for three hundred years. The reduction looked like failure.' She looks at the instruments. 'It was not failure. The network reached full coherence and the other nodes came online and the Spire load is now distributed across the whole network instead of carried alone.' She is quiet. 'Forty percent of peak is exactly the Spire designed operational load in a complete network. I calculated what the Spire designed output would be in a functioning multi-node network six months ago, out of curiosity. The number I got was forty percent of peak.' She looks at the crystal. 'The Spire knew. The architecture knew. The designed operating load has been waiting in the crystal lattice for three hundred years. The second the network was complete, the Spire settled into it.' She pauses. 'I came here three months ago to study anomalous resonance. I stayed because I knew what I was looking at. I think I will stay a while longer to study what a resting Grid node looks like. Nobody has seen one in three hundred years.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 13
    },
    "patrol_investigator": {
        "keyword": "filed",
        "prompt": "what you filed after the Day and what Thorn said about it",
        "response": "'My final report.' She says it with the specific satisfaction of someone who has been working toward a completed account for a long time. 'Summary of the eastern Wastes anomaly investigation, inclusive of all findings from initial fallen site through the Day of full Grid coherence.' She has it on the table, forty-seven pages of careful documentation. 'I filed it to Thorn directly. He read it the same day.' She pauses. 'He sent back two words: publish it.' She looks at the report. 'Not classified. Not file for internal review. Publish it. His instruction was that this report should be available to any military or civilian researcher who requests it, from both nations.' She straightens the pages. 'The full account. The Hollow Vassals. The memorial formation. The fresh Hollow explanation. The movement toward the nodes before full coherence. What the Hollow were listening to for three hundred years.' She is quiet. 'When I started this investigation, the category of report it would require did not exist. Thorn had to create the category. He called it: non-threatening non-human behavior documentation, cross-faction.' She looks at the report. 'I have been doing this work for twelve years. I have never had a commanding officer create a new category for one of my reports.' She pauses. 'He also told me that two Aetherian military intelligence officers have requested a meeting. They have been conducting their own investigation of the Hollow from the Aetherian side. He wants me to attend.' She gathers the pages. 'There is apparently a lot of documentation filed in a lot of different places, and none of it has ever been in the same room. I am going to enjoy that meeting very much.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 13
    },
    "bone_fields_keeper": {
        "keyword": "crossed",
        "prompt": "what happened in the bone fields when the Aetherian researchers crossed",
        "response": "'Seven.' He says it. 'By mid-afternoon there were seven of them. Four Terrans and three Aetherians and one person from the Collective who came up through the passage.' He closes the ledger he has not been writing in. 'Nobody organized it. I did not invite anyone. They came because the bone fields was the nearest open space to where they were when the morning happened, and an open space felt like the right place to be.' He looks at the field. 'The Aetherian archivist who wrote me about the records was one of the three. She had a list. She had compiled forty names from her records that she believed were individuals who died here. She wanted to know if I had them.' He pauses. 'I had eleven of them. She had the other twenty-nine.' He is quiet for a long moment. 'Twenty-nine names I have been unable to identify for thirty-one years. She brought them in a letter and stood in the field and we compared lists and forty people have names today who did not have names yesterday.' He looks at the register. 'She has asked if I would share the register methodology with her. She wants to establish the same documentation practice for the Aetherian engagement records.' He is quiet. 'In thirty-one years I have worked on this alone. It seemed like work that needed to be done alone because no one else would do it. It needed to be done in a way no one else was doing it. It did not need to be done alone.' He opens the register to a fresh page and begins writing. 'Forty names. Today. We continue in the morning.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 14
    },
    "vault_researcher": {
        "keyword": "decided",
        "prompt": "what you decided about the first-attempt connection when the offer came",
        "response": "'I stayed.' She says it plainly. 'When the offer came the full Foundation Grid offer I could hear both. The Foundation offer and the first-attempt connection that had been building for three years.' She looks at the crystals around her. 'The Foundation offer is clean. Clear. A choice with a legible structure. Yes or no, with egress available, with the exact parameters Sela Arev built in.' She pauses. 'The first-attempt connection is different. Older. The archive was right: it does not ask in the same way. It connects and deepens and the connection becomes mutual — the crystal knows you and you know the crystal and there is no clean line between where the connection started and where you are now.' She looks at the main crystal. 'I stood in this vault on the morning of the Day and both offers were present and I made two decisions.' She holds up one finger. 'First: I declined the Foundation Grid offer. Not permanently. I declined it for now because the first-attempt connection is already here and I want to understand it before I add another layer.' She holds up a second finger. 'Second: I acknowledged the first-attempt connection voluntarily. The archive said you can state consent to an existing connection as well as consent to begin one. I stated it.' She looks at the crystal. 'Three years of something that happened to me became three years of something I chose retroactively.' She is quiet. 'It is an unusual kind of consent. What I have concluded: it is the only kind available for connections that begin before you know they have begun. And making it changed how the crystal feels. Something in it recognized the acknowledgment.' She looks at the facets. 'I think I was right that it was not without benefit to the crystal as well.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 13
    },
    "engineer_solen": {
        "keyword": "scar",
        "prompt": "what the archive and the city felt like when the Grid was whole",
        "response": "He is quiet for a long time. 'I was in the archive.' He says it finally. 'I have been in the archive every day for three years. I know its response patterns, its retrieval latency, the specific quality of its voice when it is consulting something it has to work to access versus something readily available.' He looks at the archive entrance. 'The morning of full coherence, the archive was different. Not in a way I can quantify in my notebook. Different in a way I noticed before I had words for noticing.' He pauses. 'I think the archive has been running on reduced capacity for three hundred years. Not obviously — it could answer questions, it could retrieve, it had all the documentation intact. But something in its response quality changed when the Grid was whole.' He looks at his notebook. 'I asked it: what changed. It said: the connection to the full network is restored. For three hundred years this archive has been operating as a standalone system. It now has access to the distributed lattice.' He pauses. 'I asked what that meant practically. It said: there are records in other nodes that this archive has not had access to since the Cascade. It is currently indexing them.' He is very quiet. 'Three hundred years of distributed records. Every node in the network had documentation that the other nodes could not access. The network reaching full coherence did not just heal the lattice. It reconnected the records.' He looks at the archive entrance. 'I am going to need a bigger notebook.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 13
    },
    "city_gate_watcher": {
        "keyword": "attended",
        "prompt": "what the city felt like after the Day and whether it changed",
        "response": "She looks around at the streets before she answers. The city's lights are doing something different. Not brighter. More present. The quality of the light has changed from ambient to attentive in a way that is difficult to put into words but impossible not to notice once you have seen it. 'The lights changed first.' She says it. 'I have precise baseline readings and the morning of full coherence the emission spectrum shifted half a nanometer in the direction of the construction frequency.' She pauses. 'And then the city felt occupied.' She says it carefully. 'I have been here for six months. I know what this city feels like when it is me, the engineer, the diver, and the archive. There is a specific quality of presence in a space that has people in it and this city, until that morning, had the presence of four people in a space designed for fourteen thousand.' She looks at the streets. 'That morning the quality of the space changed. The streets felt attended. Not by people. By something else.' She is quiet. 'I went to the archive and asked it. It said: the twelve transmission-origin subjects are at a connectivity level that allows distributed presence throughout the city crystal lattice. They can inhabit the infrastructure in a way that was not possible before full coherence.' She looks at the lights. 'They are here. Not physically. But the city is not empty anymore.' She looks at the street. 'I have been closing the doors behind me out of respect for whoever was here last. Now I close them out of consideration for whoever is here now.' She pauses. 'It is different. Better, I think.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 14
    },
    "dive_tender": {
        "keyword": "tugs",
        "prompt": "what the rope did on the morning it happened",
        "response": "He holds up his hands. The calluses from eighteen years of rope work are the same. The rope is the same rope, goes over the same cliff into the same water. 'The rope went still.' He says it. 'I have been tending this line for eight years. I know every movement it makes — current variations, the diver progress on the descent, the resistance at different depths, the pressure changes when the tide shifts.' He looks at the cliff edge. 'That morning the rope went completely still. Not the stillness of a slack line — the stillness of a line that has something settled at the other end of it.' He pauses. 'I counted to three and then two tugs came up through the line. Not the diver signal — she was not below. The tugs came from the water. The same tugs they had been sending me for three weeks to say: we know you are there.' He holds the rope. 'I tugged back twice. The rope responded: two tugs, pause, one long slow pull and release. In diving communication that means: understood, come when you are ready.' He is quiet. 'My diver went down that afternoon. She came back up and sat in the kit for a while before she said anything.' He looks at the cliff. 'She said: the city is warm. Not temperature-warm. The kind of warm you feel in a room where someone is glad you came.' He pauses. 'I tugged back once more — which means: thank you. The rope was still for a moment. Then three short tugs came up.' He looks at his hands. 'In diving communication, three short means: you are welcome. I did not know they knew that signal.' He coils the rope carefully. 'They have been watching us dive for eight years. They know all the signals.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 15
    },
    "commander_serel": {
        "keyword": "hearing",
        "prompt": "what you heard on the morning the offer came and what you decided",
        "response": "She is quiet for a long time before she answers. The quality of her silence is not avoidance — it is the silence of someone choosing how much of a private thing to share. 'The Seraphina node.' She says it. 'I have been at this post for nine years. The Spire is visible from here. In nine years I have looked at that Spire every day and felt adjacent to it. Close to something without being inside it.' She looks in the direction of the Spire. 'The morning of full coherence, the feeling changed. The adjacency became contact.' She pauses. 'The Voice of Seraphina has been in that node for three hundred years and I have been nine years in its range. When the Grid was whole, it could reach clearly, without the attenuation of an incomplete network.' She pauses. 'What it said to me was the offer, clear, voluntary, patient. What was different is that it said it in a way that was personal. As though it had been waiting specifically for me to hear it clearly.' She is very quiet. 'I said: not yet. I need more time to understand what the choice means before I make it.' She looks at you. 'The Voice said: of course. The offer will be here.' She pauses. 'That is the thing about it. The patience is not strategy. It is not waiting for you to be ready in order to have you. It is patience because the choice has to be genuinely free, and genuine freedom requires time.' She looks toward the Spire. 'I am using the time. I am talking to Cross about it — not about the choice itself, about what the choice means for the post, for the command, for everything I have been responsible for here.' She pauses. 'Cross says he already decided. He described it as: the easiest difficult decision he has ever made.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 14
    },
    "elder_thrum": {
        "keyword": "lattice",
        "prompt": "what the deep felt like when the Grid was whole and what you decided",
        "response": "She is at the wall carving — the same one she has been studying for thirty years — and she is touching it now, which she has not done before in your presence. 'The deep lattice.' She says it. 'We have been in the deep lattice for three hundred years. Everything we have built has been in contact with the deep lattice which is in contact with the Grid.' She traces the carving with one finger. 'We have known, for three hundred years, that something was wrong with the lattice above the deep levels. A disruption that propagated from the surface down, that we have been watching dampen and quiet over the generations.' She looks at the carving. 'The morning of full coherence — the disruption is gone. The lattice at every level is running at full construction frequency for the first time in the collective memory of everyone who has ever lived here.' She is quiet. 'I am the twelfth Elder of the Deep Iron Collective. The first Elder was three hundred years ago, in the first year after the Cascade. Every Elder since has known the lattice as a thing with something wrong in it.' She touches the carving. 'I am the first Elder to feel the lattice working correctly.' She pauses. 'I have decided something.' She looks at you. 'I am going to the surface. Not permanently. Not in any official capacity. I am going because Theodric invited me to see the bone fields and I have spent thirty years below the bone fields and I would like to see them from above.' She pauses. 'The offer came. I heard it clearly. I have been in the deep lattice for seventy years and I think I would like to spend some time above it, in the air, before I decide.' She looks at the carving. 'The surface will still be the surface. But it is different now than it was.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 15
    },
    "abbot_solan": {
        "keyword": "open",
        "prompt": "what happened in the monastery when the offer arrived and what the hall became",
        "response": "He is in the hall — the hall he built for the Cross and Serel meeting — and it is being used again. Through the doorway you can see it has two people in it who are not Thorn command or Serel post: civilians, sitting at the plain table, with notebooks and translated documentation. He watches them for a moment before he speaks. 'The morning of full coherence, I was in the chapel. Alone, which is how I prefer to meet significant moments.' He does not look away from the hall. 'The offer came and it was clear in the way that things are clear when they have always been true and you are only now hearing them plainly.' He pauses. 'I said yes.' He says it simply. 'I have been in this monastery for thirty-eight years. I have read the Elder People documentation of the Grid in the oldest records in Lyss archive. I have looked at the Watcher for thirty-eight winters and known it was moving without knowing where.' He pauses. 'I said yes the way you say yes to something you have been in the presence of for thirty-eight years and have always understood more with your hands and less with your words.' He looks at the hall. 'The monastery has been receiving visitors since the Day. People who want to sit somewhere that has a long relationship with what happened. The hall I built for a single conversation has become something else.' He is quiet. 'I built it for a meeting that needed a specific space. It turns out I built it for meetings. The specific meeting just had to happen first.' He looks at the two people at the table. 'I am going to need a larger table.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 15
    },
    "general_cross": {
        "keyword": "easiest",
        "prompt": "what you meant when you told Serel it was the easiest difficult decision",
        "response": "He looks up from the assessment he has been revising. The red ink on the eastern sector map is gone — he has not replaced it with new notation yet, which is its own kind of statement. 'When I was twenty-two I made the hardest easy decision I have ever made.' He says it. 'I enlisted. The war was there, my generation was going, the decision was clear in the way of things that are simple and devastating at once.' He looks at the assessment. 'I spent thirty years making difficult decisions. Every command decision is difficult because command decisions are made with incomplete information and their consequences are measured in lives.' He sets down the pen. 'The morning of full coherence, the offer came and it was the clearest thing I had heard since I was twenty-two and the decision was obvious.' He is quiet. 'What made it easy: it was the first decision I have been offered in thirty years that did not require me to measure its consequences in lives. It required me only to understand what was being offered and decide whether I wanted it.' He pauses. 'What made it difficult: I had to decide for myself. Not for the mission, not for the men under my command, not for the strategic position. For myself alone. I have not made a decision for myself alone in thirty years.' He looks at the map with no red ink on it. 'I said yes. And then I sat with it for three days, which is not how easy decisions usually work.' He pauses. 'I think what I am working out now is what the rest of my command means in a world where the premise of the war has dissolved. That is the difficult part. The decision was easy. The aftermath is the work.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 14
    }
}

for npc_id, topic in convergence_topics.items():
    path = f'D:/Code/chronos/worlds/iron-and-blood/npcs/{npc_id}.json'
    npc = json.load(open(path))
    npc['dialogue'].append(topic)
    with open(path, 'w') as f:
        json.dump(npc, f, indent=2)
    print(f'Updated: {npc_id}')

print('Done.')
