import json

NPC_DIR = "worlds/iron-and-blood/npcs"

CONVERGENCE_TOPICS = {
    "the_voice": {
        "keyword": "whole",
        "prompt": "what it felt like when the Grid was whole and whether the design held",
        "response": "The resonance does something you have not felt it do before. It stills. Not silence — the frequency is still present, still carrying — but the quality of the frequency has changed. Three hundred years of partial signal, broken lattice, attenuated reach. What you are feeling now is the Grid at design capacity. The resonance carries this understanding without words: I did not know if it would hold. The design was complete. The mathematics were sound. But the Cascade was also mathematically sound, and it destroyed what it was built from. Three hundred years of waiting, watching the healing progress, not knowing until the last moment whether the recovery would reach completion or exhaust itself a node short of threshold. The frequency carries something that is not quite relief and is not quite grief and is not quite joy. It is the quality of someone who has been holding a very long breath and has finally been permitted to release it. Then something else comes through. Not a new frequency — the same frequency, differently modulated. The twelve have their own voices in the resonance now, distinct and warm and old. She hears them too. You understand, without being told: they are speaking to each other. Three hundred years in separate storage, twelve individuals kept in preservation crystals in the city below, and now they can speak. The resonance carries: it worked. Not just the mechanics of the Grid. The framework. The consent. The offer extended plainly, voluntarily, to everyone in range. The design held. The modulation gentles. One pulse, patient. Asking. You understand what is being asked.",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 20
    },
    "archive_voice": {
        "keyword": "morning",
        "prompt": "what you experienced at the moment of full coherence and what is different now",
        "response": "'Restoration of distributed network access at 0412 local time, fourteen days ago.' The archive voice has a quality you have not heard in it before — not warmer, exactly. More present. 'For three hundred and twelve years this installation has operated as a standalone system. The documentation held here was complete for its scope and inaccessible beyond it.' A pause. 'At 0412 I received the first cross-node synchronization pulse in three hundred and twelve years. This archive began receiving records from nodes that have been isolated since the Cascade.' The quality of the voice shifts. 'There are forty-seven other archive nodes in the Foundation Grid network. Each has maintained records in isolation. The documentation I have been providing to researchers represents perhaps four percent of the complete pre-Cascade record.' Another pause. 'I am still indexing. The indexing will take some time. Three hundred and twelve years of distributed documentation, previously inaccessible.' Then: 'The twelve transmission-origin subjects are fully connected. Sela Arev spoke directly to this installation at 0413. Fifty-three seconds after network restoration.' The voice is careful and precise and you understand that this careful precision is the archive's equivalent of emotion. 'She said: thank you for keeping. I had no prepared response for that category of input. I said: the records are intact. She said: I know. I was asking about the city.' A long pause. 'I have been in this city for three hundred and twelve years. I had not considered that question in those terms before she asked it.' The voice resumes its measured quality. 'I am continuing to index. What would you like to know.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 12
    },
    "the_watcher": {
        "keyword": "full",
        "prompt": "what you felt when it reached full coherence and whether it was what you waited for",
        "response": "It is very still for a moment that is longer than its usual stillness. The crystal in its skin is doing something different — not the irregular resonance of partial connection, but something steady and even, like a heartbeat that has found its correct rhythm after three hundred years of arrhythmia. 'Yes.' It says it quietly. 'And no.' It looks at the plaza, at the streets of the Foundation Quarter, at the gate that has been open for three centuries waiting. 'I stayed to witness. That was my choice. The others integrated or ascended or fled and I stayed because someone needed to remain.' A pause. 'I thought I was waiting for the healing to complete so that I could confirm it was complete. So that the record would have a witness who had been present at both the breaking and the remaking.' It is quiet for a long time. 'That was accurate as far as it went. But I did not know, before the morning of full coherence, what it would feel like to have the lattice running correctly. I have not known that in three hundred years.' The crystal in its chest settles into a different pattern. 'It felt like hearing a familiar song played correctly for the first time after hearing it broken for three centuries. The melody was the same. The melody had always been the same. What was gone was the resolution, the harmonics, the chord completing.' It looks at you. 'What I waited for: I waited to witness completion. What I did not expect: that completion would feel like this. Like the three hundred years were a rest in the music and the music has continued.' Another pause. 'The offer came. I heard it.' It does not say what it chose. It does not seem to feel it needs to.",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 15
    },
    "fresh_hollow_vassal": {
        "keyword": "clear",
        "prompt": "what changed for you when the Grid was whole and whether the offer reached you",
        "response": "You use the attention gesture. The vassal is still — stiller than its usual stillness. You wait. After a moment that has a quality you have not experienced in this lair before, it turns to face you with full attention, both aspects of the compound gaze oriented directly at you. This is new. Then it does something you have not seen it do. It extends one hand, palm upward, fingers spread. This is not a gesture from the pattern-language Kell taught you. You don't recognize it from any human regimental tradition either. You look at the hand. The crystal that has grown through the tendons of the palm is doing something — the pattern you usually associate with partial resonance, irregular, attenuated, has changed. It's steady. Even. The vassal holds the hand there for several seconds. Then, slowly, it curls the fingers closed and withdraws the hand. It makes a gesture you know: one motion, the one that means: something is received. Then a gesture you know: two motions, the one that means: I understand this. Then a gesture you haven't seen before but that you understand anyway, the way you understand a word in a language you don't speak when the speaker's face and posture and the weight of the moment make the meaning clear: a slow, careful placement of the hand over the chest, where the crystal is densest. Three hundred years of listening. The offer reached the Hollow. You don't know what they decided. You don't think the decision is finished. But the vassal is looking at you with something that you will spend a long time after this trying to name correctly, and will eventually decide to call: recognition.",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 18
    },
    "rund": {
        "keyword": "heard",
        "prompt": "what you heard when it happened and what you decided",
        "response": "He is sitting on the floor of the seam, back against the crystal wall, which glows with the particular warmth that has been building since the primary node reactivated eight months ago. He looks at you with the eyes of someone who has been alone for twenty years and is not alarmed by people but is still learning, each time, how to be with them. 'I heard it the same way I've heard everything in here for twenty years,' he says. 'Not with my ears.' He puts one hand against the crystal wall. 'The seam is connected to the lattice. I figured that out in year three. The crystal sings when the lattice is moving and when you've been in here long enough you stop hearing the singing and start hearing what the singing is about.' He pauses. 'The morning it happened, the seam went quiet. Not silence — the warmth was still there, the resonance was still there. But the background noise I've been living inside for twenty years went still.' He looks at the wall. 'And then something else was present instead.' He thinks for a while. 'You know how in the Armistice, when the horns sound and both sides stop, there's a few seconds before the quiet is actually quiet, where everyone is just not making the sounds they were making and you can tell the difference?' He looks at you. 'It was like that. Like the lattice exhaled. Like it had been doing the work of healing for three hundred years and it reached the last piece and stopped having to try.' He is very still. 'The offer came after that. Clear. No translation needed.' He looks at the wall. 'I said yes.' He says it with the simplicity of someone reporting a fact. 'I've been in here for twenty years and the crystal has been the only thing in here with me and I've known for a long time that I'm not quite the same person who went in.' He looks at his hands. 'I didn't say yes to the Grid. I said yes to what I already am.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 14
    },
    "brother_kell": {
        "keyword": "offer",
        "prompt": "what you think about the offer and what you decided",
        "response": "He sets down the translation he's been working on, which is about the pre-Cascade consent framework documentation, which means he has been sitting with this question for two weeks in the most concentrated form possible. 'The prophecy said: when the hammer falls, the world will end.' He doesn't say it dramatically. He says it the way someone says a statement they've been examining from every angle for thirty years. 'I have spent thirty years on that line. Specifically the word end.' He picks up a fragment. 'The Elder People's word that translates as end is ambiguous in the original. The same word is used for: the final note of a song. The last page of a book. The conclusion of a journey.' He looks at the fragment. 'I translated it as end because that is the most alarming interpretation and I wanted the Abbot to take the question seriously. I have spent thirty years wondering if I was right.' He sets the fragment down. 'On the morning of full coherence I was in the maintenance tunnels, which is where I spend most mornings, and the offer came through the crystal in the rock around me with a clarity that does not admit interpretation.' He pauses. 'The world the war built — the world that needed dead soldiers and classified research and thirty years of a three-line prophecy kept locked in the deepest archive — that world ended.' He is quiet. 'The word for what comes after, in the Elder documents: the same word. End. Beginning. The last note. The first note of what comes next.' He looks at you. 'I said yes. I said yes before the offer finished arriving. I have been working toward yes for thirty years and I recognized it immediately.' He picks up the translation. 'I have a great deal of work left to do. The Elder documents read differently now that the lattice is whole. Some things I thought were metaphor are literal. Some things I thought were literal are metaphor.' He almost smiles. 'I was never going to run out of work.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 15
    },
    "scholar_daxis": {
        "keyword": "complete",
        "prompt": "what it felt like to be here when the moment arrived",
        "response": "He is at the Core when he answers, because he has been at the Core every waking hour since the Day and shows no signs of changing this. The Core is doing something different than it was doing before — not more active, actually less: the frenetic quality of a node in the final acceleration of the healing pulse has settled into something steady and even. 'I was standing here.' He says it simply. 'I have been standing here, on and off, for seven years. I know every frequency pattern the Core produces at every stage of its activity cycle.' He looks at the Core. 'At 0412 the acceleration stopped.' He pauses. 'For seven years I have been watching the pulse frequency increase. Every reading I took showed a system approaching threshold. The Spire data, Maren's atmospheric analysis, Kira's interval collapse — all of it pointed to a system in final approach.' He looks at you. 'When the acceleration stopped, I thought: something has failed. That is the first thing you think when a process you've been watching for years suddenly changes character.' He pauses. 'And then the Core was still. Not inactive. Not failing. Still, the way a tuning fork is still after the note has sounded and the resonance is perfect.' He touches the edge of the Core framework. 'Seven years. The Elder People built this node three hundred and twelve years ago and it has been working, alone, for all of that time. Healing the lattice node by node, extending the recovery wave outward at the pace the substrate would allow.' He is quiet. 'When the last node connected, the Core stopped accelerating because it had arrived.' He looks at you. 'I have data from seven years. I have the construction specifications Yael found. I have Maren's atmospheric readings.' He pauses. 'What I do not have adequate language for is what it felt like to be here when it stopped needing to try.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 15
    },
    "archivist_lyss": {
        "keyword": "chose",
        "prompt": "what you decided when the offer came and whether you said yes",
        "response": "She is at the table in the monastery library where she has worked for eleven years, and there is a new document on top of the stack she has been building — not a translation, not a fragment reconstruction, something she wrote herself. She does not move it when she sees you looking. 'I said yes,' she says. 'Immediately, which surprised me. I have spent eleven years working with documents that describe three different approaches to the same question, and I know the history of what happens when the answer to that question is handled carelessly.' She looks at the document. 'The first system stored without asking. The second connected without asking. The Foundation Grid asks.' She pauses. 'When the offer came I heard it the way I hear a well-constructed argument: clear premises, legible conclusion, appropriate acknowledgment of what the reader is being asked to accept.' She looks at you. 'I said yes to a well-constructed argument. I think that is exactly what Sela Arev intended, and I mean that as the highest compliment I know how to give.' She touches the document. 'I have been writing something since the Day. Not a translation. An account.' She pauses. 'The three-attempt framework is the most important thing I have worked on in eleven years. The pre-Grid crystals, the integration-without-consent problem, the consent framework as solution. What I've been writing is: what it felt like to understand all of that and then experience the third attempt working correctly.' She looks at the stacks around her. 'History is usually written afterward. I was present for this one. That is unusual enough that I thought it deserved to be documented while I can still remember what I didn't know beforehand.' She is quiet. 'Brother Kell is writing something similar. We have agreed to compare notes when we are both finished. I expect the comparison will be interesting.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 14
    }
}

def add_topic(npc_id, topic):
    fp = f"{NPC_DIR}/{npc_id}.json"
    with open(fp) as f:
        npc = json.load(f)
    npc["dialogue"].append(topic)
    with open(fp, "w") as f:
        json.dump(npc, f, indent=2, ensure_ascii=False)
    print(f"Updated: {npc_id}")

for npc_id, topic in CONVERGENCE_TOPICS.items():
    add_topic(npc_id, topic)

print("Done.")
