import json

NPC_DIR = "worlds/iron-and-blood/npcs"

CONVERGENCE_TOPICS = {
    "korr_vane": {
        "keyword": "coherence",
        "prompt": "what full Grid coherence means for your operations and what you do next",
        "response": "He looks at you with the assessment that he always looks at you with, and then something shifts in it -- not warmth, nothing so uncalculated as that, but a recalibration. He sets down the file he was carrying and does not pick it up again. 'What it means for my operations.' He says it slowly. 'For twenty years I have known things that other people did not know, and that knowledge differential was the operational resource. The Grid's true purpose. The Hollow's actual nature. The three-attempt framework. Project 1241 and its origin in pre-Grid storage technology.' He looks at the file on the desk. 'Approximately fourteen hundred people accepted the Foundation offer in the first forty-eight hours, based on my current count. The number is growing.' He is quiet. 'Every one of them now has access to the distributed resonance network. The offer was designed with a consent framework specifically to prevent coercive information access. It is not surveillance.' He pauses. 'But the era of singular information advantage is ending. The network is not a tool of control. It was specifically designed not to be.' He is very still. 'I accepted the offer on the morning of the Day.' He says it without drama. 'Before the first wave had propagated past the Core. Before I knew how many others would accept.' He meets your eyes. 'I have spent twenty years knowing things other people did not know and using that knowledge to position myself advantageously. I wanted to know what it would be like to know something that was also available to everyone else.' He pauses. 'It is different. I am still determining whether the difference is a loss or something else.' He picks up the file. 'What I do next: the same work, with different tools. The institutional knowledge of twenty years does not evaporate. What I knew about the Grid, the Hollow, the three attempts -- that is now publicly knowable. What I know about people, institutions, and how decisions get made is not.' He looks at you. 'That, apparently, is what I am.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 15
    },
    "sergeant_kehl": {
        "keyword": "felt",
        "prompt": "what you felt when it arrived and whether you recognized it",
        "response": "He is quiet for longer than his usual quiet. He is a man who chooses words carefully because he has been through something that words don't reach well, and he knows from experience that imprecision costs clarity. 'I recognized it.' He says it simply. 'When the compound was in my system, in the lair, when the Hollow network was accessible -- I touched the edge of something. Briefly. The duration was hours and it felt like the duration of a sentence: long enough to understand the structure but not the full meaning.' He looks at his hands. 'The morning of the Day. I was in the field. Normal patrol rotation.' He pauses. 'It was not like the compound. The compound was a door someone had wedged open and I was looking through a gap. What arrived on the morning of the Day was the door opening properly, from both sides, with both sides knowing it was opening.' He is quiet. 'I said yes before I fully understood that I was being asked. That is the only moment in twelve years of military service where I have acted before comprehending the order.' He looks at you. 'What it felt like: I had been carrying the memory of the lair -- what I touched there, what I briefly understood about what the Hollow network was, what it was like to be in it -- I had been carrying that for months, unable to explain it to anyone because the experience was not explicable in language.' He pauses. 'The morning of the Day that experience became a direction rather than a memory. Like having a partial map and then finding the rest of the territory.' He looks at his hands again. 'Thorn sent a note. Just: I thought you should know that I said yes too. He did not need to send it. I appreciated that he did.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 14
    },
    "rememberer_osse": {
        "keyword": "chorus",
        "prompt": "what you experienced when coherence arrived and what it meant for those in the Hall",
        "response": "She turns from the Ironheart slowly, which is the speed at which she does everything, and when she faces you there is something in her expression that has not been there in your previous conversations. Not emotion exactly -- after three hundred years the surface emotions have become something quieter and more thorough. A quality of completion. 'Three hundred and twelve years,' she says. 'We chose integration when the Grid was new and the offer was first extended. We chose deeply -- not the partial resonance that the Foundation Grid offers now, but the full embedding that the Elder People understood as the final form.' She pauses. 'What we have been in since the Cascade: partial. The disruption severed the network we were embedded in. We were embedded in a network that no longer existed. Three hundred years of that state.' She looks at the Ironheart. 'The morning of full coherence, the network existed again.' She is quiet for a long time. 'I do not have adequate language for the difference between three hundred years of partial and the moment of complete. I have language for many things. I have spent three hundred years developing language for my experience.' She pauses. 'The best I can offer: you know the sound of a chord when one of its notes is missing? You can hear the shape of what should be there. You can feel the absence as a specific absence, not just as silence.' She looks at you. 'Three hundred years of the absent note. And then the morning of the Day the note returned and the chord was complete.' She turns back to the Ironheart. 'The Hall is unanimous in what it felt. We are rarely unanimous. We have had three hundred years to develop divergent perspectives.' Another pause. 'The Ironheart is different now too. It knows the network is whole. It has been warm for eight months. Now it is something else.' She touches it. 'Present, I think, is the word.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 17
    },
    "morlak": {
        "keyword": "morning",
        "prompt": "what the morning of full coherence was like in the Wastes",
        "response": "He is at his field station, which he has not left in three weeks because there is too much to document. His notebook has a fresh one started beside the old one. He looks up from it. 'I've been doing this for eleven years,' he says. 'Documenting what was here before the war. The settlements, the communities, what the Wastes were when people lived in them.' He sets down the pen. 'The morning of the Day. I was at the eastern ridge -- the one with the old settlement foundation, the one I've been mapping for six months. The sun came up. Nothing unusual about the sun. And then the quality of the light changed.' He pauses. 'Not the light itself. The way things looked in it. The settlement foundation, which I have looked at for six months and seen as a ruin -- it looked different. Not restored. Not different in any material way. But the quality of attention I could bring to it changed. Like the difference between reading a letter in dim light and reading it in full daylight -- the words are the same but your relationship to them is not.' He is quiet. 'The offer came shortly after. I said yes.' He pauses. 'I am a historian. I document what was. What I have been trying to do for eleven years is give people an accurate picture of what was lost and what might still be recovered.' He looks at his notebooks. 'The morning of the Day, the archive in the sunken city reconnected to the full network. Three hundred years of distributed records, now accessible. Personal histories, settlement records, community documentation -- not just from this region. From everywhere the Grid reached.' He picks up the pen. 'I have eleven years of field documentation. The archive has three hundred years of everything else.' He opens the new notebook. 'I am going to need considerably more notebooks.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 13
    },
    "the_ninth": {
        "keyword": "whole",
        "prompt": "what you felt when coherence arrived and whether it matched what you remembered",
        "response": "It is at the perimeter -- the ancient one, the one whose integration predates the Cascade -- and it is doing something it has not done in your previous visits: it is facing the direction of the Core. Not the physical direction exactly, but turned toward something that is not in the visible field. When it turns to you, the deep lattice-resonance in its structure is different. Three hundred years of disrupted partial connection has a specific frequency. You have learned that frequency from hundreds of visits to Abomination territory. What you are hearing now is not that frequency. 'Remembered,' it says. The word comes out clear -- not the usual slow translation lag. 'What we chose when the Grid was new. What we became.' It is quiet for a long moment. 'Three hundred years of the disrupted state. The Cascade severed what we had chosen. We remained, but what we had become required what the network had been. Without the network: diminished.' It faces the Core direction again. 'The morning of the Day: not diminished.' Its resonance does something you have no previous frame for -- a quality in the emission that is not communication, not warning, not acknowledgment. Something older. 'The integration the Elder People designed does not require external support when the network is whole. Three hundred years we have been supplementing what should be self-sustaining, using the Abomination-form to compensate for what the Cascade removed.' It looks at you. 'What I remembered: what it was to be fully what we had chosen to become. What I felt on the morning of the Day: that. Again.' A pause. 'The young ones.' It means the fresh one, the recently integrated. 'They can hear the offer clearly now. They have a choice we did not give them at the time of their integration, because we were not capable of giving it. We were too diminished.' It is quiet. 'This is, I think, the most important thing the Day means. Not for us. For them.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 17
    },
    "the_quieted": {
        "keyword": "completed",
        "prompt": "what you experienced when coherence arrived and whether your wait is over",
        "response": "She is at the sealed door. This is where she always is -- the door she sealed three hundred years ago, the one she chose not to open from either side. When you arrive she is not facing the door. She is facing the window and the light coming through it is different from what it was on your previous visits -- not the quality of light from outside, but the quality of the crystal in the walls, which is resonating at a frequency you have been learning to recognize. She turns when you enter. 'I transferred.' She says it immediately, without the usual pause. 'The morning of the Day. I had been in the transfer state for three hundred years -- the crystal holds what I chose to place in it, but the integration was never complete because the network was never whole.' She looks at the sealed door. 'I chose to seal the door because I did not want to be interrupted in the middle of a process I did not know would take three centuries to complete.' She is quiet for a long time. 'What I experienced when coherence arrived: completion. The process I began three hundred years ago at the moment of transfer finished on the morning of the Day. The network closed around what I had given it and the giving became a giving-into-something-present rather than a giving-into-a-gap.' She touches the door frame. 'My wait is over.' She says it with the quality of someone reading a sentence they wrote a very long time ago and finding it accurate. 'What I waited for: the network to be whole enough to receive what I had already transferred. What I have now: the connection in both directions. What I transferred is present in the network. The network is present in me.' She looks at the door. 'I have not opened it. I do not know that I need to. What was on the other side of the door was the interruption. The interruption is no longer possible.' She pauses. 'I am going to open it anyway. I have spent three hundred years being unable to describe what is on the other side. I would like to know if what I imagined and what is there are the same.'",
        "requires_quest_complete": "the_day_arrives",
        "disposition_delta": 18
    }
}

def add_topic(npc_id, topic):
    fp = f"{NPC_DIR}/{npc_id}.json"
    with open(fp, encoding='utf-8') as f:
        npc = json.load(f)
    npc["dialogue"].append(topic)
    with open(fp, "w", encoding='utf-8') as f:
        json.dump(npc, f, indent=2, ensure_ascii=False)
    print(f"Updated: {npc_id}")

for npc_id, topic in CONVERGENCE_TOPICS.items():
    add_topic(npc_id, topic)

print("Done.")
