import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import wasm from 'vite-plugin-wasm';
import topLevelAwait from 'vite-plugin-top-level-await';
import path from 'path';

// Dev-only: src/wasm/ is generated by wasm-pack and has its own package.json,
// which makes Vite treat it as a node package and bypass HMR + ETags.
// This plugin forces no-store headers AND strips ETags/Last-Modified so the browser
// always re-fetches the WASM binary and JS glue after a rebuild.
function noCacheWasm() {
  return {
    name: 'no-cache-wasm',
    configureServer(server: any) {
      server.middlewares.use((req: any, res: any, next: any) => {
        if (req.url && req.url.includes('/wasm/')) {
          res.setHeader('Cache-Control', 'no-store, must-revalidate');
          res.setHeader('Pragma', 'no-cache');
          // Remove conditional-request headers from the incoming request so
          // Vite never sends 304 Not Modified for wasm assets.
          delete req.headers['if-none-match'];
          delete req.headers['if-modified-since'];
        }
        next();
      });
    },
  };
}

export default defineConfig({
  plugins: [react(), wasm(), topLevelAwait(), noCacheWasm()],
  resolve: {
    alias: { '@': path.resolve(__dirname, 'src') },
  },
  optimizeDeps: {
    // WASM modules must be excluded from Vite's pre-bundling
    exclude: ['chronos-wasm'],
  },
});
