import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import wasm from 'vite-plugin-wasm';
import path from 'path';

// Dev-only: src/wasm/ is generated by wasm-pack and has its own package.json,
// which makes Vite treat it as a node package and bypass HMR + ETags.
// This plugin forces no-store headers AND strips ETags/Last-Modified so the browser
// always re-fetches the WASM binary and JS glue after a rebuild.
function noCacheWasm() {
  return {
    name: 'no-cache-wasm',
    configureServer(server: any) {
      server.middlewares.use((req: any, res: any, next: any) => {
        if (req.url && req.url.includes('/wasm/')) {
          res.setHeader('Cache-Control', 'no-store, must-revalidate');
          res.setHeader('Pragma', 'no-cache');
          // Remove conditional-request headers from the incoming request so
          // Vite never sends 304 Not Modified for wasm assets.
          delete req.headers['if-none-match'];
          delete req.headers['if-modified-since'];
        }
        next();
      });
    },
  };
}

export default defineConfig({
  // Dev and most builds serve from root. The GitHub Pages deploy sets
  // VITE_BASE=/chronos/ so asset URLs resolve under the project subpath.
  base: process.env.VITE_BASE || '/',
  plugins: [react(), wasm(), noCacheWasm()],
  resolve: {
    alias: { '@': path.resolve(__dirname, 'src') },
  },
  optimizeDeps: {
    // WASM modules must be excluded from Vite's pre-bundling
    exclude: ['chronos-wasm'],
  },
  build: {
    rollupOptions: {
      output: {
        manualChunks: (id) => {
          // Separate the React/Zustand vendor bundle so it can be cached
          // independently from app code. Users only re-download the smaller
          // app chunk when content changes.
          if (id.includes('node_modules/react') || id.includes('node_modules/react-dom') || id.includes('node_modules/zustand')) {
            return 'vendor';
          }

          // Group world data into one chunk per (world, category).
          //
          // `engine-wasm.ts` globs world JSON lazily, which by default emits one
          // chunk per file — 400+ sub-10KB requests on first load, since Iron &
          // Blood alone is 154 quests, 72 NPCs and 71 rooms. Grouping matches how
          // the data is actually consumed: `initEngine` awaits every category for
          // one world in a single `Promise.all`, so a whole category is always
          // fetched together or not at all.
          //
          // Category rather than whole-world granularity because class data is
          // needed earlier than the rest — `listPlayableClasses` runs on the
          // character-creation screen, before `initEngine`. Keeping classes
          // separate means class select doesn't drag 154 quests down with it.
          //
          // Per-world laziness is preserved: picking Iron & Blood still fetches
          // nothing belonging to Millbrook, and a world added later gets its own
          // chunks with no change here.
          //
          // world.json is deliberately unmatched below — it's globbed eagerly for
          // the world-select screen, so it belongs in the entry bundle rather than
          // stranded in a chunk of its own.
          const worldPath = id.replace(/\\/g, '/');
          const categoryFile = worldPath.match(/\/worlds\/([^/]+)\/([^/]+)\/[^/]+\.json$/);
          if (categoryFile) return `world-${categoryFile[1]}-${categoryFile[2]}`;
          const manifestFile = worldPath.match(/\/worlds\/([^/]+)\/manifest\.json$/);
          if (manifestFile) return `world-${manifestFile[1]}-manifest`;
        },
      },
    },
  },
});
